Site1: "https://fim.temple.edu"
  test1: "Test login"
    url: "https://fim.temple.edu/idp/profile/cas/login;jsessionid=B163D40C0D02FA2F015D50856DA4B8B9?execution=e1s1"
    method: "POST"
      case1: "test login with email and password"
        input:
          -
            rule: "#username"
            value: ["test@gmail.com", "test@"]
          -
            rule: "#password"
            value: ["my_correct_password", "something"]
        output:
          httpStatus: 200
