-
  name: "Stackoverflow.com site"
  tests:
    -
      name: "Test login"
      url: "https://stackoverflow.com/users/login?ssrc=head&returnurl=https%3a%2f%2fstackoverflow.com%2fquestions%2f42136253%2fbeautifulsoup-and-request-post"
      method: "POST"
      cases:
        -
          name: "test login with email and password"
          params:
            email: "test@gmail.com"
            password: "my_correct_password"

          output:
            status_code: 200
        -
          name: "test login with incorrect email format"
          params:
            email: "test@g"
            password: "something"
          output:
            status_code: 400